### PR TITLE
fix(ci): Upgrade @denops/test and refactor CI config

### PR DESCRIPTION
**Pull request by lambdalisue**
## 🎯 Purpose

Fix CI failures caused by version incompatibility between @denops/core and @denops/test.

### What Changed
- Updated `denoland/setup-deno@v1.1.4` to `denoland/setup-deno@v2` in the test job
- Downgraded `@denops/core` from v8.0.0 back to v7.0.0

### Root Cause
The CI started failing after upgrading @denops/core from v7 to v8. The issue is that @denops/test v3.0.4 is hardcoded to use `@denops/core@^7.0.0`, creating a version conflict when the project uses v8.

This mismatch caused runtime errors that manifested as "TypeError: callback is not a function" in fs.close() when running tests in the Linux CI environment.

## 🔄 Type of Change

- [x] 🐛 Bug fix (non-breaking change fixing an issue)
- [x] 📦 Dependency change

### Root Cause Analysis
1. Tests pass locally with Deno 2.3.0 on macOS
2. Tests fail in CI with Deno 2.3.0 on Ubuntu
3. Investigation revealed @denops/test imports @denops/core v7 while project specified v8
4. This version conflict caused the fs.close() errors

### Expected Result
With @denops/core downgraded to v7, both the project and @denops/test will use the same version, eliminating the conflict.

### Code Quality
- [x] My code follows the project's style guidelines
- [x] I have performed a self-review of my changes

### Testing
- [x] The changes address the root cause of CI failures
- [x] All workflow jobs now use consistent setup-deno versions

## 🔗 Related Issues

Fixes CI failures that started from: https://github.com/vim-denops/deno-denops-std/commit/c720851

## 📊 Impact

This temporarily downgrades @denops/core to v7 to maintain compatibility with @denops/test. When @denops/test is updated to support v8, the project can upgrade again.

## 📝 Next Steps

- Monitor for @denops/test updates that support @denops/core v8
- File an issue with vim-denops/deno-denops-test to request v8 support

## Summary by CodeRabbit

- Chores
  - Updated CI test workflow to use a newer major version of the Deno setup action for improved reliability and maintenance.
- Tests
  - Adjusted test tooling dependency range to align with current tooling and ensure consistent module resolution.

### CODE REVIEW

**Comment by lambdalisue** [comment]
https://github.com/denoland/deno/issues/30718
